name: A11y Tests

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
  workflow_dispatch:

jobs:

  a11y-test:
    name: Run A11y Tests
    if: contains(github.event.pull_request.labels.*.name, 'a11y-tests')
    runs-on: ${{ fromJSON(vars.RUNNER) }}
    timeout-minutes: 40
    steps:
      - uses: browser-actions/setup-chrome@b94431e051d1c52dcbe9a7092a4f10f827795416 # v2.1.0
        with:
          install-dependencies: true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 #v4.2.0
        with:
          run_install: false
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm install
      - name: Run a11y tests
        env:
          # this will generate the test reports but causes tests to pass even when there a11y failures
          ENABLE_A11Y_MIDDLEWARE_REPORTER: true
        run: pnpm test-a11y
      - name: Consolidate ember a11y reports
        run: |
          mkdir ember-a11y-reports
          jq -s 'map(.[])' ./ui/admin/ember-a11y-report/*.json > ember-a11y-reports/admin.json
          jq -s 'map(.[])' ./ui/desktop/ember-a11y-report/*.json > ember-a11y-reports/desktop.json
      - name: Output ember a11y test report summary (admin)
        run: 'cat ember-a11y-reports/admin.json | jq "map({moduleName,testName,routes,urls,violations: .violations | map({id, nodes: .nodes | map({failureSummary, targets: .[].[]?.relatedNodes?.[]?.target? })}) })"'
      - name: Output ember a11y test report summary (desktop)
        run: 'cat ember-a11y-reports/desktop.json | jq "map({moduleName,testName,routes,urls,violations: .violations | map({id, nodes: .nodes | map({failureSummary, targets: .[].[]?.relatedNodes?.[]?.target? })}) })"'
      - name: Upload ember a11y reports
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ember-a11y-reports
          path: ./ember-a11y-reports
      - name: Report a11y test results status
        if: always()
        # fail CI when the combined array length of admin and desktop a11y reports is not 0
        run: |
          EMBER_A11Y_FAILURE_COUNT=$(jq -s 'map(.[]) | length' ember-a11y-reports/admin.json ember-a11y-reports/desktop.json)
          echo "$EMBER_A11Y_FAILURE_COUNT ember-a11y test failures"
          if [ "$EMBER_A11Y_FAILURE_COUNT" != '0' ]; then
            exit 1
          fi
